### PR TITLE
splitVBF

### PR DESCRIPTION
**Pull request by RaulRPrado**
splitVBF is based on mergeVBF.

I had to add mergeVBF and splitVBF to all VTS in the Makefile. Not sure why mergeVBF wasn't there already.

### CODE REVIEW

**Comment by GernotMaier** [comment]
mergeVBF is used by hardly any user of Eventdisplay, this was the reason why it was not in the target list for VERITAS. Would it make sense to have a separate target called maybe 'vbftools' or something similar?

**Comment by RaulRPrado** [comment]
> mergeVBF is used by hardly any user of Eventdisplay, this was the reason why it was not in the target list for VERITAS. Would it make sense to have a separate target called maybe 'vbftools' or something similar?

Yes, makes sense. I'll do that.

**Comment by RaulRPrado** [comment]
@GernotMaier , have you had a look at the code?
The only trick part is that I find the simulation run header beforehand and write it to all the sub files. 
Apart from that, I just split the packets uniformly.

Does that sound right?

**Comment by GernotMaier** [comment]
The code looks fine to me, but I am by far no expert. Did you cross check by comparing the analysis results of a complete file with the file splitted by half?

**Pull request merged**
